### ISSUE TITLE
[Proposal] replace Yoga with vislyhq/stretch

### ISSUE THREAD

**Issue by xzilja** [lunarraid/react-pixi-layout#9]
I was planing to start work on something similar as this library today until I found it. Just tried it out, really amazing work!
During my research for layout engine I considered Yoga as well, but also found https://github.com/vislyhq/stretch

After some tests and researching both, I came to conclusion that `stretch` seems like a lighter, more performant alternative, with slightly easier api.

Hence this proposal issue, perhaps this is something you'd like to research as well. If you end up liking it, I am down collaborate on implementation :) If not, feel free to close the issue.

**Comment by lunarraid** [comment]
I too had looked into stretch a while back, but had considerable difficulty getting it running, then ran into some bugs when I did. I finally chose to use `typeflex` instead as it made dependencies much easier to work with.
